version: "2"

services:

  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - postgres_test
    environment:
      - NODE_ENV=$NODE_ENV
    env_file:
      - .env.test

  postgres:
    image: postgres:11-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: echouser
      POSTGRES_PASSWORD: echopass

  postgres_test:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: echouser
      POSTGRES_PASSWORD: echopass
